- data.js
- scheme.js
created a query under directory and a separate base query called biography
> Adding biographies to the api

- data.js
Reverts SchoolofComputerScience/scs-api#3
> Revert "added the pris env var"

- data.js
- scheme.js
Updated attributes due to field name changes in the biographies collection.
> fix biographies fields

- data.js
- scheme.js
Add performance supervisor scids to fulfill issue #1
> add perf supervisor scids

- data.js
- scheme.js
Adding Programs data to the GraphQL API
> Programs update

- data.js
- scheme.js
Adding Departments To The GraphQL API, so we can use the Departments Collection to make a Department Filter Component.
> Adding Departments To The GraphQL API

- data.js
- scheme.js
Schema of the collection was changed. This updates allow the data to be returned successfully.
> Updating Departments To The GraphQL API

- .gitignore
- data.js
- scheme.js
Please don't merge the pull request since this requires an update to the database. I'll merge it... just need a blessing or recommendation for mods.
> Add and rename directory relationship fields

- scheme.js
Added logic to calculate next semester's semester-code and used that to pull in all courses by a certain scid. This should review upcoming courses for any certain member.
> Adding Courses For Members In The GraphQl API

- data.js
- scheme.js
and fix the data type in scheme for primary position
> add new SCS attributes

- data.js
- scheme.js
Adding a GraphQL option to receive the _NEXT_ semester's code that can be used in any consuming application.
> Creating GraphQL Request For Semester Code

- data.js
- scheme.js
This could be @cs.cmu.edu, @cmu.edu, @andrew.cmu.edu, or other.
> Add attribute for preferred display email

- data.js
This should be followed by renaming the collection in mLab.
> rename directory collection ref

- data.js
- scheme.js
Adding a GraphQL API call to validate a scid
> Adding GraphQL API Call for Validation Of Scids

- src/data/programs.js
- src/data/research.js
- src/types/programs.js
- src/types/research.js
Updated GraphQL API for Research Areas and Programs after updates to the collection for each.
> Updating GraphQL For Research Areas and Programs

- src/data/research.js
- src/types/research.js
Make course ID's and titles available from the researchAreas endpoint.
> add courses to research areas

- package.json
- src/data/index.js
- src/data/members.js
- src/data/positions.js
- src/db.js
- src/queries/index.js
- src/queries/members.js
- src/queries/positions.js
- src/server.js
- src/types/member.js
- src/types/position.js
Changing source of data from MongoDB to MySQL. Updated Directory and Positions to reflect new data coming from MySQL tables.
1. Change your local `.env` to get new variables for your local environment (check with me to get values)
2. Use the Browser Interface to test for Members and their Positions `localhost:5000/graph`
> Change Source to MySQL, Updated Members And Positions

- src/content/outreach.md
update content for outreach to mirror current site
> update content for outreach to mirror current site

- src/content/doctoral-admissions.md
- src/content/masters-admissions.md
- src/content/undergraduate-admissions.md
Updated the content to match current SCS site. Also fixed some textual resizing issues and typos.
> Updated the content on the admissions pages

- src/content/doctoral-admissions.md
- src/content/masters-admissions.md
- src/content/undergraduate-admissions.md
- src/queries/publications.js
Updated the publications query so that it can return all publications regardless of members.
> New publications
